listener 8883
protocol mqtt

cafile /Volumes/Data Drive/Projects/Professor's projects/Frederick Sheldon/Post-Quantum-Secure-MQTT/pqc_mqtt_project/certs/ca.crt
certfile /Volumes/Data Drive/Projects/Professor's projects/Frederick Sheldon/Post-Quantum-Secure-MQTT/pqc_mqtt_project/certs/broker.crt
keyfile /Volumes/Data Drive/Projects/Professor's projects/Frederick Sheldon/Post-Quantum-Secure-MQTT/pqc_mqtt_project/certs/broker.key

require_certificate false
allow_anonymous true

tls_version tlsv1.3

log_type all
